name: Site Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: site_output
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v1
        with:
          name: site_output

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: site_output
